version: "3"
services:

  application:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    ports :
     - "80:80"
    volumes:
     - ./:/var/www/html/
    links:
     - database
    container_name: PAApp
  database:
      image: mysql:5.7
      ports:
       - "3306:3306"
      volumes:
       - ./Database:/var/lib/mysql
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=root
      expose:
        - 3306
      container_name: PADb